/**
 * Information about a file changed in the PR
 */
export interface ChangedFile {
  /** File path relative to repository root */
  path: string;
  /** Type of change */
  changeType: 'added' | 'modified' | 'deleted' | 'renamed';
  /** Number of lines added */
  additions: number;
  /** Number of lines deleted */
  deletions: number;
  /** Previous file path (only for renamed files) */
  previousPath?: string;
  /** File content (may be omitted for large files) */
  content?: string;
  /** Patch/diff for this file */
  patch?: string;
}

/**
 * Information about the pull request being reviewed
 */
export interface PullRequestInfo {
  /** PR number */
  number: number;
  /** PR title */
  title: string;
  /** PR description/body */
  body: string;
  /** Repository owner */
  owner: string;
  /** Repository name */
  repo: string;
  /** Base branch (target branch) */
  baseBranch: string;
  /** Head branch (source branch) */
  headBranch: string;
  /** Head commit SHA */
  headSha: string;
  /** PR author username */
  author: string;
  /** Labels applied to the PR */
  labels: string[];
  /** Whether this PR was generated by AI */
  isAiGenerated: boolean;
  /** AI generation context (prompts, model used, etc.) */
  aiContext?: {
    model?: string;
    prompts?: string[];
    generatedAt?: Date;
    generatorVersion?: string;
  };
}

/**
 * Context passed to each review step during execution
 */
export interface ReviewContext {
  /** Information about the pull request */
  pr: PullRequestInfo;
  /** List of files changed in this PR */
  changedFiles: ChangedFile[];
  /** Working directory where the PR code is checked out */
  workingDirectory: string;
  /** GitHub API token for making API calls */
  githubToken: string;
  /** Environment variables available to review steps */
  env: Record<string, string>;
  /** Custom data that can be set by previous review steps */
  sharedData: Record<string, unknown>;
  /** Logger for review steps to write output */
  logger: {
    info: (message: string) => void;
    warn: (message: string) => void;
    error: (message: string) => void;
    debug: (message: string) => void;
  };
}
