/**
 * AI-generated PR detection system
 *
 * Analyzes PRs to determine if they were generated by AI, using multiple heuristics:
 * - Commit message patterns (Co-Authored-By: Claude, Ralph events)
 * - PR description markers
 * - Factory worker metadata
 */

export interface AIDetectionResult {
  /** Whether the PR appears to be AI-generated */
  isAIGenerated: boolean;
  /** Confidence score (0-100) */
  confidence: number;
  /** Detected indicators of AI generation */
  indicators: AIIndicator[];
  /** Metadata about the detection */
  metadata: {
    /** AI system detected (claude, ralph, factory, etc.) */
    aiSystem?: string;
    /** Model version if detected */
    modelVersion?: string;
    /** Worker ID if from factory */
    workerId?: string;
  };
}

export interface AIIndicator {
  /** Type of indicator */
  type: 'commit-coauthor' | 'commit-message' | 'pr-description' | 'pr-label' | 'pr-metadata';
  /** Description of what was found */
  description: string;
  /** Confidence weight (0-100) for this indicator */
  weight: number;
  /** Location where indicator was found */
  location: string;
}

export interface PRData {
  /** PR title */
  title: string;
  /** PR body/description */
  body: string;
  /** Commit messages */
  commits: CommitData[];
  /** PR labels */
  labels: string[];
  /** PR metadata (custom fields, comments, etc.) */
  metadata?: Record<string, unknown>;
}

export interface CommitData {
  /** Commit message */
  message: string;
  /** Commit author */
  author: string;
  /** Commit co-authors */
  coAuthors?: string[];
}

/**
 * AIDetector analyzes PRs to detect AI-generated content
 */
export class AIDetector {
  /**
   * Analyze a PR to detect if it was AI-generated
   * @param pr PR data to analyze
   * @returns Detection result with confidence score
   */
  async detect(pr: PRData): Promise<AIDetectionResult> {
    const indicators: AIIndicator[] = [];

    // Check commits for AI markers
    for (const commit of pr.commits) {
      const commitIndicators = this.checkCommit(commit);
      indicators.push(...commitIndicators);
    }

    // Check PR description for AI markers
    const descriptionIndicators = this.checkPRDescription(pr.body, pr.title);
    indicators.push(...descriptionIndicators);

    // Check PR labels for AI markers
    const labelIndicators = this.checkPRLabels(pr.labels);
    indicators.push(...labelIndicators);

    // Check PR metadata for factory worker info
    const metadataIndicators = this.checkPRMetadata(pr.metadata);
    indicators.push(...metadataIndicators);

    // Calculate confidence score (weighted average)
    const totalWeight = indicators.reduce((sum, ind) => sum + ind.weight, 0);
    const confidence = indicators.length > 0 ? Math.min(100, totalWeight) : 0;

    // Determine if AI-generated (threshold: 50)
    const isAIGenerated = confidence >= 50;

    // Extract metadata
    const metadata = this.extractMetadata(indicators, pr);

    return {
      isAIGenerated,
      confidence,
      indicators,
      metadata,
    };
  }

  /**
   * Check commit for AI markers
   */
  private checkCommit(commit: CommitData): AIIndicator[] {
    const indicators: AIIndicator[] = [];

    // Check for Claude co-authorship
    const coAuthors = commit.coAuthors || [];
    for (const coAuthor of coAuthors) {
      if (coAuthor.includes('claude') || coAuthor.includes('anthropic.com')) {
        indicators.push({
          type: 'commit-coauthor',
          description: `Claude co-author detected: ${coAuthor}`,
          weight: 80,
          location: `commit: ${commit.message.split('\n')[0]}`,
        });
      }
    }

    // Check for Ralph events in commit message
    if (commit.message.includes('[RALPH:')) {
      indicators.push({
        type: 'commit-message',
        description: 'Ralph event marker found in commit message',
        weight: 90,
        location: `commit: ${commit.message.split('\n')[0]}`,
      });
    }

    // Check for factory worker patterns
    if (commit.message.match(/worker-[a-f0-9-]+/i)) {
      indicators.push({
        type: 'commit-message',
        description: 'Factory worker ID pattern detected',
        weight: 85,
        location: `commit: ${commit.message.split('\n')[0]}`,
      });
    }

    return indicators;
  }

  /**
   * Check PR description for AI markers
   */
  private checkPRDescription(body: string, title: string): AIIndicator[] {
    const indicators: AIIndicator[] = [];

    // Check for factory metadata markers
    if (body.includes('AI Factory') || body.includes('ai-factory')) {
      indicators.push({
        type: 'pr-description',
        description: 'AI Factory reference found in PR description',
        weight: 70,
        location: 'PR body',
      });
    }

    // Check for Claude Code reference
    if (body.includes('Claude Code') || body.includes('claude.com/claude-code')) {
      indicators.push({
        type: 'pr-description',
        description: 'Claude Code reference found in PR description',
        weight: 75,
        location: 'PR body',
      });
    }

    // Check for spec-based PR pattern
    if (body.includes('## Summary') && body.includes('## Test plan')) {
      indicators.push({
        type: 'pr-description',
        description: 'Structured PR template (Summary/Test plan) detected',
        weight: 40,
        location: 'PR body',
      });
    }

    // Check for AI generation metadata
    if (body.includes('Generated with') || body.match(/🤖.*generated/i)) {
      indicators.push({
        type: 'pr-description',
        description: 'AI generation marker found',
        weight: 80,
        location: 'PR body',
      });
    }

    return indicators;
  }

  /**
   * Check PR labels for AI markers
   */
  private checkPRLabels(labels: string[]): AIIndicator[] {
    const indicators: AIIndicator[] = [];

    const aiLabels = [
      'ai-generated',
      'ai',
      'claude',
      'factory',
      'ralph',
      'automated',
    ];

    for (const label of labels) {
      if (aiLabels.some(aiLabel => label.toLowerCase().includes(aiLabel))) {
        indicators.push({
          type: 'pr-label',
          description: `AI-related label detected: ${label}`,
          weight: 70,
          location: 'PR labels',
        });
      }
    }

    return indicators;
  }

  /**
   * Check PR metadata for factory worker info
   */
  private checkPRMetadata(metadata?: Record<string, unknown>): AIIndicator[] {
    const indicators: AIIndicator[] = [];

    if (!metadata) {
      return indicators;
    }

    // Check for factory worker metadata
    if (metadata.workerId) {
      indicators.push({
        type: 'pr-metadata',
        description: 'Factory worker ID found in metadata',
        weight: 95,
        location: 'PR metadata',
      });
    }

    // Check for AI generation context
    if (metadata.aiContext || metadata.generationContext) {
      indicators.push({
        type: 'pr-metadata',
        description: 'AI generation context found in metadata',
        weight: 90,
        location: 'PR metadata',
      });
    }

    return indicators;
  }

  /**
   * Extract metadata from indicators
   */
  private extractMetadata(
    indicators: AIIndicator[],
    pr: PRData
  ): AIDetectionResult['metadata'] {
    const metadata: AIDetectionResult['metadata'] = {};

    // Detect AI system
    if (indicators.some(i => i.description.includes('Claude'))) {
      metadata.aiSystem = 'claude';
    } else if (indicators.some(i => i.description.includes('Ralph'))) {
      metadata.aiSystem = 'ralph';
    } else if (indicators.some(i => i.description.includes('Factory'))) {
      metadata.aiSystem = 'factory';
    }

    // Extract model version from commits or PR body
    const modelMatch = pr.body.match(/claude-(?:sonnet|opus)-[\d-]+/i);
    if (modelMatch) {
      metadata.modelVersion = modelMatch[0];
    }

    // Extract worker ID from metadata
    if (pr.metadata?.workerId && typeof pr.metadata.workerId === 'string') {
      metadata.workerId = pr.metadata.workerId;
    }

    return metadata;
  }
}
