import type { DetectionResult, PRContext } from '@factory/shared';

/**
 * Detects if a PR was generated by AI based on various signals
 */
export class PRDetector {
  /**
   * Detect if a PR is AI-generated
   * @param context PR context including commits, branch, labels
   * @returns Detection result with confidence score and reasons
   */
  detect(context: PRContext): DetectionResult {
    const reasons: string[] = [];
    let confidence = 0;

    // Check commit co-authors
    const hasClaudeCoAuthor = this.checkCommitCoAuthors(context.commits);
    if (hasClaudeCoAuthor) {
      reasons.push('Commit contains "Co-Authored-By: Claude Sonnet 4.5"');
      confidence += 0.7;
    }

    // Check branch name pattern
    const branchPattern = this.checkBranchPattern(context.branch);
    if (branchPattern) {
      reasons.push(`Branch matches AI pattern: ${context.branch}`);
      confidence += 0.2;
    }

    // Check labels
    const hasAILabel = this.checkLabels(context.labels);
    if (hasAILabel) {
      reasons.push('PR has "ai-generated" label');
      confidence += 0.1;
    }

    // Confidence capped at 1.0
    confidence = Math.min(confidence, 1.0);

    const isAI = confidence >= 0.5;

    return {
      isAI,
      confidence,
      reasons,
      metadata: {},
    };
  }

  /**
   * Check if commits contain Claude co-author signature
   */
  private checkCommitCoAuthors(commits: PRContext['commits']): boolean {
    const claudePattern = /Co-Authored-By:\s*Claude\s+Sonnet\s+4\.5/i;
    return commits.some((commit: { sha: string; message: string; author: string }) => claudePattern.test(commit.message));
  }

  /**
   * Check if branch name matches AI-generated patterns
   */
  private checkBranchPattern(branch: string): boolean {
    // Pattern: ai/issue-* or ai/task-* or ai/*
    const patterns = [
      /^ai\/issue-\d+/,
      /^ai\/task-\d+/,
      /^ai\/.+/,
    ];
    return patterns.some((pattern) => pattern.test(branch));
  }

  /**
   * Check if PR has AI-related labels
   */
  private checkLabels(labels: string[]): boolean {
    const aiLabels = ['ai-generated', 'ai', 'automated', 'bot'];
    return labels.some((label) =>
      aiLabels.some((aiLabel) => label.toLowerCase().includes(aiLabel))
    );
  }
}
